 ALTER TABLE "AIR"."AVION" MODIFY ("LOCALISATION" DEFAULT 'Paris') ;
 ALTER TABLE "AIR"."AVION" ADD CONSTRAINT "PK_AVION" PRIMARY KEY 
 ("NUMAVION") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 FREELISTS 1 FREELIST 
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" LOGGING ENABLE ;
 ALTER TABLE "AIR"."AVION" ADD CONSTRAINT "CON_CHECK" CHECK (CAPACITE 
 IN('140','180','200','250','300','320','360','380','450','460')) 
 ENABLE NOVALIDATE ;
 ALTER TABLE "AIR"."PILOTE" ADD CONSTRAINT "PK_PILOTE" PRIMARY KEY 
 ("NUMPILOTE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 FREELISTS 1 FREELIST 
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" LOGGING ;
 ALTER TABLE "AIR"."VOL" MODIFY ("NUMPILOTE" DEFAULT NULL ) ;
 ALTER TABLE "AIR"."VOL" ADD CONSTRAINT "PK_VOL" PRIMARY KEY 
 ("NUMVOL") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 FREELISTS 1 FREELIST 
 GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" LOGGING ENABLE ;
 ALTER TABLE "AIR"."VOLPIL#" ADD CONSTRAINT "PLT_PARIS" CHECK 
 (Villearr='Paris') ENABLE NOVALIDATE ;
 ALTER TABLE "AIR"."VOLPIL##" ADD CONSTRAINT "PLT_NO_PARIS" CHECK 
 (Villearr NOT IN ('Paris')) ENABLE NOVALIDATE ;
 ALTER TABLE "AIR"."VOL" ADD CONSTRAINT "FK_NUMAVION" FOREIGN KEY 
 ("NUMAVION") REFERENCES "AVION" ("NUMAVION") ENABLE NOVALIDATE ;
 ALTER TABLE "AIR"."VOL" ADD CONSTRAINT "FK_NUMPILOTE" FOREIGN KEY 
 ("NUMPILOTE") REFERENCES "PILOTE" ("NUMPILOTE") ENABLE NOVALIDATE ;
 ALTER TABLE "AIR"."AVION" ENABLE CONSTRAINT "CON_CHECK" ;
 ALTER TABLE "AIR"."VOLPIL#" ENABLE CONSTRAINT "PLT_PARIS" ;
 ALTER TABLE "AIR"."VOLPIL##" ENABLE CONSTRAINT "PLT_NO_PARIS" ;
 ALTER TABLE "AIR"."VOL" ENABLE CONSTRAINT "FK_NUMAVION" ;
 ALTER TABLE "AIR"."VOL" ENABLE CONSTRAINT "FK_NUMPILOTE" ;