CREATE INDEX "AIR"."IND_NUMAVION" ON "VOL" ("NUMAVION" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" 
LOGGING ;
CREATE INDEX "AIR"."REVIND_NUMPILOTE" ON "VOL" ("NUMPILOTE" ) REVERSE 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"AIR_IND" LOGGING ;