
REM  CREATE TABLE "AIR"."AVION" ("NUMAVION" NUMBER(6, 0) NOT NULL ENABLE, 
REM  "NOMAVION" VARCHAR2(20) NOT NULL ENABLE, "CAPACITE" NUMBER(3, 0) NOT 
REM  NULL ENABLE, "LOCALISATION" VARCHAR2(45), "DATEMISESERVICE" DATE) 
REM  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 1048576 
REM  NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "AIR_DATA" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "AIR"."AVION" MODIFY ("LOCALISATION" DEFAULT 'Paris') ;
REM  ... 5 rows
CONNECT AIR;
CREATE UNIQUE INDEX "AIR"."PK_AVION" ON "AVION" ("NUMAVION" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" 
LOGGING ;
REM  ALTER TABLE "AIR"."AVION" ADD CONSTRAINT "PK_AVION" PRIMARY KEY 
REM  ("NUMAVION") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
REM  STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 FREELISTS 1 FREELIST 
REM  GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" LOGGING ENABLE ;
REM  ALTER TABLE "AIR"."AVION" ADD CONSTRAINT "CON_CHECK" CHECK (CAPACITE 
REM  IN('140','180','200','250','300','320','360','380','450','460')) 
REM  ENABLE NOVALIDATE ;
REM  CREATE TABLE "AIR"."COMPETENT_IOT" ("NUMPILOTE" NUMBER(4, 0) NOT NULL 
REM  ENABLE, "NUMTYP" VARCHAR2(4) NOT NULL ENABLE, CONSTRAINT 
REM  "PK_COMPETENT_IOT" PRIMARY KEY ("NUMPILOTE", "NUMTYP") ENABLE ) 
REM  ORGANIZATION INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 
REM  1048576 NEXT 1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 
REM  BUFFER_POOL DEFAULT) TABLESPACE "AIR_DATA" LOGGING NOCOMPRESS 
REM  PCTTHRESHOLD 50 ;
REM  ... 0 rows
REM  CREATE TABLE "AIR"."PILOTE" ("NUMPILOTE" NUMBER(4, 0) NOT NULL 
REM  ENABLE, "NOMPILOTE" VARCHAR2(20) NOT NULL ENABLE, "ADRESSE" 
REM  VARCHAR2(50), "DATECREATION" DATE NOT NULL ENABLE, "DATEDERMAJ" 
REM  TIMESTAMP (6) NOT NULL ENABLE, "CV" CLOB) PCTFREE 10 PCTUSED 40 
REM  INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 1048576 NEXT 1048576 
REM  MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) 
REM  TABLESPACE "AIR_DATA" LOGGING NOCOMPRESS LOB ("CV") STORE AS 
REM  BASICFILE (TABLESPACE "AIR_DATA" ENABLE STORAGE IN ROW CHUNK 8192 
REM  RETENTION NOCACHE LOGGING STORAGE(INITIAL 1048576 NEXT 1048576 
REM  MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
REM  ... 3 rows
CREATE UNIQUE INDEX "AIR"."PK_PILOTE" ON "PILOTE" ("NUMPILOTE" ) PCTFREE 
10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" 
LOGGING ;
REM  ALTER TABLE "AIR"."PILOTE" ADD CONSTRAINT "PK_PILOTE" PRIMARY KEY 
REM  ("NUMPILOTE") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
REM  STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 FREELISTS 1 FREELIST 
REM  GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" LOGGING ;
REM  CREATE TABLE "AIR"."VOL" ("NUMVOL" CHAR(6) NOT NULL ENABLE, 
REM  "NUMAVION" NUMBER(6, 0) NOT NULL ENABLE, "NUMPILOTE" NUMBER(4, 0), 
REM  "VILLEDEP" VARCHAR2(35) NOT NULL ENABLE, "VILLEARR" VARCHAR2(35) NOT 
REM  NULL ENABLE, "HEUREDEP" CHAR(5), "HEUREARR" CHAR(5)) PCTFREE 10 
REM  PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE(INITIAL 1048576 NEXT 
REM  1048576 MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL 
REM  DEFAULT) TABLESPACE "AIR_DATA" LOGGING NOCOMPRESS ;
REM  ALTER TABLE "AIR"."VOL" MODIFY ("NUMPILOTE" DEFAULT NULL ) ;
REM  ... 8 rows
CREATE UNIQUE INDEX "AIR"."PK_VOL" ON "VOL" ("NUMVOL" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" 
LOGGING ;
CREATE INDEX "AIR"."IND_NUMAVION" ON "VOL" ("NUMAVION" ) PCTFREE 10 
INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 
FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" 
LOGGING ;
CREATE INDEX "AIR"."REVIND_NUMPILOTE" ON "VOL" ("NUMPILOTE" ) REVERSE 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"AIR_IND" LOGGING ;
REM  ALTER TABLE "AIR"."VOL" ADD CONSTRAINT "PK_VOL" PRIMARY KEY 
REM  ("NUMVOL") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
REM  STORAGE(INITIAL 516096 NEXT 516096 MINEXTENTS 1 FREELISTS 1 FREELIST 
REM  GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE "AIR_IND" LOGGING ENABLE ;
REM  CREATE GLOBAL TEMPORARY TABLE "AIR"."VOLPIL#" ("NUMVOL" CHAR(6) NOT NULL 
REM  ENABLE, "NOMPILOTE" VARCHAR2(20) NOT NULL ENABLE, "VILLEDEP" VARCHAR2(35) 
REM  NOT NULL ENABLE, "VILLEARR" VARCHAR2(35) NOT NULL ENABLE) ON COMMIT DELETE 
REM  ROWS ;
REM  ALTER TABLE "AIR"."VOLPIL#" ADD CONSTRAINT "PLT_PARIS" CHECK 
REM  (Villearr='Paris') ENABLE NOVALIDATE ;
REM  CREATE GLOBAL TEMPORARY TABLE "AIR"."VOLPIL##" ("NUMVOL" CHAR(6) NOT NULL 
REM  ENABLE, "VILLEARR" VARCHAR2(35) NOT NULL ENABLE, "HEUREARR" CHAR(5)) ON 
REM  COMMIT PRESERVE ROWS ;
REM  ALTER TABLE "AIR"."VOLPIL##" ADD CONSTRAINT "PLT_NO_PARIS" CHECK 
REM  (Villearr NOT IN ('Paris')) ENABLE NOVALIDATE ;
REM  ALTER TABLE "AIR"."VOL" ADD CONSTRAINT "FK_NUMAVION" FOREIGN KEY 
REM  ("NUMAVION") REFERENCES "AVION" ("NUMAVION") ENABLE NOVALIDATE ;
REM  ALTER TABLE "AIR"."VOL" ADD CONSTRAINT "FK_NUMPILOTE" FOREIGN KEY 
REM  ("NUMPILOTE") REFERENCES "PILOTE" ("NUMPILOTE") ENABLE NOVALIDATE ;
CREATE BITMAP INDEX "AIR"."IND_LOCALISATION" ON "AVION" ("LOCALISATION" ) 
PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(INITIAL 516096 NEXT 516096 
MINEXTENTS 1 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT) TABLESPACE 
"AIR_IND" LOGGING ;
REM  ALTER TABLE "AIR"."AVION" ENABLE CONSTRAINT "CON_CHECK" ;
REM  ALTER TABLE "AIR"."VOLPIL#" ENABLE CONSTRAINT "PLT_PARIS" ;
REM  ALTER TABLE "AIR"."VOLPIL##" ENABLE CONSTRAINT "PLT_NO_PARIS" ;
REM  ALTER TABLE "AIR"."VOL" ENABLE CONSTRAINT "FK_NUMAVION" ;
REM  ALTER TABLE "AIR"."VOL" ENABLE CONSTRAINT "FK_NUMPILOTE" ;
