alter system switch logfile;                                                                                                                                                                                                                                   
alter tablespace SYSTEM begin backup;                                                                                                                                                                                                                          
host copy E:\ORACLE\ORADATA\PROD\SYSTEM01.DBF F:\backup\backup_hot_ts                                                                                                                                                                                          
alter tablespace SYSTEM end backup;                                                                                                                                                                                                                            
alter tablespace SYSAUX begin backup;                                                                                                                                                                                                                          
host copy E:\ORACLE\ORADATA\PROD\SYSAUX01.DBF F:\backup\backup_hot_ts                                                                                                                                                                                          
alter tablespace SYSAUX end backup;                                                                                                                                                                                                                            
alter tablespace USERS begin backup;                                                                                                                                                                                                                           
host copy E:\ORACLE\ORADATA\PROD\USERS01.DBF F:\backup\backup_hot_ts                                                                                                                                                                                           
alter tablespace USERS end backup;                                                                                                                                                                                                                             
alter tablespace AIR_DATA begin backup;                                                                                                                                                                                                                        
host copy E:\ORACLE\ORADATA\PROD\AIR_D1.DBF F:\backup\backup_hot_ts                                                                                                                                                                                            
host copy E:\ORACLE\ORADATA\PROD\AIR_D2 F:\backup\backup_hot_ts                                                                                                                                                                                                
alter tablespace AIR_DATA end backup;                                                                                                                                                                                                                          
alter tablespace AIR_IND begin backup;                                                                                                                                                                                                                         
host copy E:\ORACLE\ORADATA\PROD\AIR_I1.DBF F:\backup\backup_hot_ts                                                                                                                                                                                            
alter tablespace AIR_IND end backup;                                                                                                                                                                                                                           
alter tablespace GESCOM_DATA begin backup;                                                                                                                                                                                                                     
host copy E:\ORACLE\ORADATA\PROD\GESCOM_D1.DBF F:\backup\backup_hot_ts                                                                                                                                                                                         
alter tablespace GESCOM_DATA end backup;                                                                                                                                                                                                                       
alter tablespace GESCOM_IND begin backup;                                                                                                                                                                                                                      
host copy E:\ORACLE\ORADATA\PROD\GESCOM_I1.DBF F:\backup\backup_hot_ts                                                                                                                                                                                         
alter tablespace GESCOM_IND end backup;                                                                                                                                                                                                                        
alter tablespace GESCOM_ARCHI begin backup;                                                                                                                                                                                                                    
host copy E:\ORACLE\ORADATA\PROD\GESCOM_D2.DBF F:\backup\backup_hot_ts                                                                                                                                                                                         
alter tablespace GESCOM_ARCHI end backup;                                                                                                                                                                                                                      
alter tablespace GCOM_DATA begin backup;                                                                                                                                                                                                                       
host copy E:\ORACLE\ORADATA\PROD\GCOM_D1.DBF F:\backup\backup_hot_ts                                                                                                                                                                                           
alter tablespace GCOM_DATA end backup;                                                                                                                                                                                                                         
alter tablespace GESCOM begin backup;                                                                                                                                                                                                                          
host copy E:\ORACLE\ORADATA\PROD\GESCOM01.DBF F:\backup\backup_hot_ts                                                                                                                                                                                          
host copy E:\ORACLE\ORADATA\PROD\GESCOM02.DBF F:\backup\backup_hot_ts                                                                                                                                                                                          
alter tablespace GESCOM end backup;                                                                                                                                                                                                                            
alter system switch logfile;                                                                                                                                                                                                                                   
alter database backup controlfile to 'F:\backup\backup_hot_ts\control.ctl'                                                                                                                                                                                     
REUSE;                                                                                                                                                                                                                                                         
exit;                                                                                                                                                                                                                                                          
