alter system switch logfile;                                                                                                                                                                                                                                   
alter database begin backup;                                                                                                                                                                                                                                   
HOST copy E:\ORACLE\ORADATA\PROD\SYSTEM01.DBF F:\backup\backup_hot_db                                                                                                                                                                                          
HOST copy E:\ORACLE\ORADATA\PROD\SYSAUX01.DBF F:\backup\backup_hot_db                                                                                                                                                                                          
HOST copy E:\ORACLE\ORADATA\PROD\UNDOTBS01.DBF F:\backup\backup_hot_db                                                                                                                                                                                         
HOST copy E:\ORACLE\ORADATA\PROD\USERS01.DBF F:\backup\backup_hot_db                                                                                                                                                                                           
HOST copy E:\ORACLE\ORADATA\PROD\AIR_D1.DBF F:\backup\backup_hot_db                                                                                                                                                                                            
HOST copy E:\ORACLE\ORADATA\PROD\AIR_I1.DBF F:\backup\backup_hot_db                                                                                                                                                                                            
HOST copy E:\ORACLE\ORADATA\PROD\GESCOM_D1.DBF F:\backup\backup_hot_db                                                                                                                                                                                         
HOST copy E:\ORACLE\ORADATA\PROD\GESCOM_I1.DBF F:\backup\backup_hot_db                                                                                                                                                                                         
HOST copy E:\ORACLE\ORADATA\PROD\AIR_D2 F:\backup\backup_hot_db                                                                                                                                                                                                
HOST copy E:\ORACLE\ORADATA\PROD\GESCOM_D2.DBF F:\backup\backup_hot_db                                                                                                                                                                                         
HOST copy E:\ORACLE\ORADATA\PROD\UNDOTBS02.DBF F:\backup\backup_hot_db                                                                                                                                                                                         
HOST copy E:\ORACLE\ORADATA\PROD\GCOM_D1.DBF F:\backup\backup_hot_db                                                                                                                                                                                           
HOST copy E:\ORACLE\ORADATA\PROD\GESCOM01.DBF F:\backup\backup_hot_db                                                                                                                                                                                          
HOST copy E:\ORACLE\ORADATA\PROD\GESCOM02.DBF F:\backup\backup_hot_db                                                                                                                                                                                          
alter database end backup;                                                                                                                                                                                                                                     
alter system switch logfile;                                                                                                                                                                                                                                   
alter database backup controlfile to  'F:\backup\backup_hot_db\control01_backup.ctl '                                                                                                                                                                          
REUSE;                                                                                                                                                                                                                                                         
exit;                                                                                                                                                                                                                                                          
